server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  datasource:
    url: "jdbc:mysql://localhost:3307/erm_demo?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&characterEncoding=utf8&useUnicode=true"
    username: root
    password: root
  liquibase:
    url: "jdbc:mysql://localhost:3307/erm_demo"
    enabled: true
    user: root
    password: root
    change-log: classpath:db/changelog/changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
feign:
  client:
    system-service:
        url: https://uaa-new.dev.apusplatform.com
    department-service:
        url: https://resources-service.dev.apusplatform.com
    employee-service:
        url: https://reactive-erp-gateway.dev.apusplatform.com
  config:
    default:
      connect-timeout: 5000
      read-timeout: 5000
      logger-level: full

current-domain: apodio.dev.apusplatform.com
access-token: eyJraWQiOiJlZGUzMThjZC1kZmIwLTQ2NDAtYjM4Zi03YzdkMmQzOTVkOGUiLCJhbGciOiJSUzI1NiJ9.eyJ0ZW5hbnRfaWQiOiIyMDEiLCJzdWIiOiJhcG9kaW9AZ21haWwuY29tIiwiaXNfb3duZXIiOnRydWUsImlzcyI6Imh0dHA6Ly8xMC4wLjEuMjA3OjgwODEiLCJhdXRob3JpdGllcyI6WyJNYW51ZmFjdG9yeSIsIkJMRE5NIl0sImF1ZCI6InRlc3QiLCJkZWZhdWx0X3RlbmFudF9pZCI6MjAxLCJuYmYiOjE3NTcyOTczNzcsImlzX3JlZ2lzdGVyIjp0cnVlLCJkZWZhdWx0X2Jpel9hcHBfaWQiOjEwLCJ1c2VyX2lkIjo1OCwib3JnX2lkIjozMDIsInNjb3BlIjpbImdhdGV3YXkiXSwiZGVmYXVsdF9vcmdfaWQiOjMzMDAsImV4cCI6MTc1ODE2MTM3NywiaWF0IjoxNzU3Mjk3Mzc3LCJqdGkiOiJhMTdjNzY5YS1jZjJmLTRmYjctOTc0OS02OTYzOTgyYmFhNjYifQ.h0g13Y29IN6p7VQiW_WmY9yaOrTFF0NfZMR2IMqPhmS1ymaQsF8ZpqSH8sBEu_GQT3CYq-VVAKROXIuFgJ3Flu7b0zOd_c-xdetiY_K7rHg8WvoqsOQ7HNmxxFoca7_9kveqGrw_nAlTOuC9eeR35QbvCKKAB8SGNXVm_O983iAPvn2rUoVWt9XkVuicZA1E0Y8a1ahZzOC9T_W6VK8IySnOH6JgxRql021aapYiuYBJLRXmsPUUHIdfKiORM4bbaNnjmN0qQQ5aIXfCJrdpkXlm-tryPZB_r3CwhR0ePFzWa_E_4uApIL1LzRYbT63BRUziQJsAXdlgcq6t-HAwLQ
file:
  upload:
    directory: D:\code\storeFile
